#!/bin/bash

# Blank line for clear output
echo

# Basic info
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATE=$(date '+%F %T')

# OS info
source /etc/os-release
OS="$NAME $VERSION"

# Uptime
UPTIME=$(uptime -p)

# CPU info
CPU=$(sudo lshw -class processor 2>/dev/null | grep product | head -n1 | cut -d: -f2)

# RAM info
RAM=$(free -h | grep Mem | tr -s ' ' | cut -d' ' -f2)

# Disk info
DISK=$(sudo lshw -class disk 2>/dev/null | grep product | head -n1 | cut -d: -f2)

# Video info
VIDEO=$(sudo lshw -class display 2>/dev/null | grep product | head -n1 | cut -d: -f2)

# Network info
GATEWAY=$(ip r | grep default | cut -d' ' -f3)
INTERFACE=$(ip r | grep default | cut -d' ' -f5)
IPADDR=$(ip a show $INTERFACE | grep inet | head -n1 | tr -s ' ' | cut -d' ' -f3 | cut -d/ -f1)
DNS=$(grep nameserver /etc/resolv.conf | head -n1 | cut -d' ' -f2)

# Users
USERS=$(who | cut -d' ' -f1 | sort | uniq | tr '\n' ',' | sed 's/,$//')

# Disk space
DISKSPACE=$(df -h --output=target,avail | tail -n +2)

# Process count
PROCS=$(ps -e | wc -l)

# Load averages
LOAD=$(uptime | cut -d: -f5)

# Listening ports
PORTS=$(ss -tuln | grep LISTEN | tr -s ' ' | cut -d' ' -f5 | cut -d: -f2 | sort -n | uniq | tr '\n' ',' | sed 's/,$//')

# UFW status
UFW=$(sudo ufw status | head -n1)

# Report
echo "System Report for $HOSTNAME generated by $USERNAME, on $DATE"
echo
echo "System Information"
echo "------------------"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "Disk(s): $DISK"
echo "Video: $VIDEO"
echo "Host Address: $IPADDR"
echo "Gateway IP: $GATEWAY"
echo "DNS Server: $DNS"
echo
echo "System Status"
echo "-------------"
echo "Users Logged In: $USERS"
echo "Disk Space:"
echo "$DISKSPACE"
echo "Process Count: $PROCS"
echo "Load Averages: $LOAD"
echo "Listening Network Ports: $PORTS"
echo "UFW Status: $UFW"

echo
